<a href="https://colab.research.google.com/github/Praachisingh29/mymans-batcave/blob/main/DL_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Input and Output
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

# Initialize weights
np.random.seed(42)
W1 = np.random.randn(2,4)
W2 = np.random.randn(4,1)

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return x*(1-x)

learning_rate = 0.1

# Training
for epoch in range(10000):

    # Forward
    hidden = sigmoid(np.dot(X, W1))
    output = sigmoid(np.dot(hidden, W2))

    # Error
    error = y - output

    # Backpropagation
    d_output = error * sigmoid_derivative(output)
    hidden_error = np.dot(d_output, W2.T)
    d_hidden = hidden_error * sigmoid_derivative(hidden)

    # Update weights
    W2 += learning_rate * np.dot(hidden.T, d_output)
    W1 += learning_rate * np.dot(X.T, d_hidden)

print("Predictions:")
print(output)

Predictions:
[[0.09621289]
 [0.92302491]
 [0.9231145 ]
 [0.06383597]]


In [2]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def swish(x):
    return x * sigmoid(x)

# Example
X = np.array([[1,2],
              [3,4]])

weights = np.random.randn(2,3)

z = np.dot(X, weights)
output = swish(z)

print(output)

[[-0.25828484 -0.07522197 -0.27455608]
 [-0.27263593 -0.00054772 -0.07638771]]


In [3]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train/255.0
X_test = X_test/255.0

model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train, y_train, epochs=5)

loss, accuracy = model.evaluate(X_test, y_test)

print("Test Accuracy:", accuracy)

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Epoch 1/5


/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9292 - loss: 0.2438
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9693 - loss: 0.0995
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9790 - loss: 0.0672
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9840 - loss: 0.0521
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - accuracy: 0.9878 - loss: 0.0396
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9762 - loss: 0.0758
Test Accuracy: 0.9761999845504761


In [4]:
import numpy as np

X = np.array([[1,2]])

W1 = np.array([[0.2,0.4],
               [0.5,0.6]])

W2 = np.array([[0.7],
               [0.8]])

def sigmoid(x):
    return 1/(1+np.exp(-x))

hidden_input = np.dot(X, W1)
hidden_output = sigmoid(hidden_input)

final_input = np.dot(hidden_output, W2)
final_output = sigmoid(final_input)

print("Output:")
print(final_output)

Output:
[[0.7691614]]


In [5]:
import numpy as np

def compute_loss(X, y, weights):
    predictions = np.dot(X, weights)
    loss = np.mean((predictions - y)**2)
    return loss

X = np.array([[1,2],
              [3,4]])

y = np.array([[5],
              [11]])

weights = np.array([[1],
                    [2]])

loss = compute_loss(X, y, weights)

print("Loss:", loss)

Loss: 0.0


In [6]:
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist

(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

X_train = X_train/255.0
X_test = X_test/255.0

model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train, y_train, epochs=10)

loss, accuracy = model.evaluate(X_test, y_test)

print("Accuracy:", accuracy)

29515/29515 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
26421880/26421880 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
5148/5148 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
4422102/4422102 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8126 - loss: 0.5289
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8541 - loss: 0.4017
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8667 - loss: 0.3676
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8734 - loss: 0.3446
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8781 - loss: 0.3311
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8815 - loss: 0.3196
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8848 - loss: 0.3087
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8882 - loss: 0.2989
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8910 - loss: 0.2925
Epoch 10/10
1875/187

In [13]:
import tensorflow as tf

url = "https://storage.googleapis.com/mledu-datasets/cats_and_dogs_filtered.zip"

path = tf.keras.utils.get_file(
    "cats_and_dogs_filtered.zip",
    origin=url,
    extract=True
)

print(path)

import os

dataset_dir = os.path.join(os.path.dirname(path), "cats_and_dogs_filtered")

train_dir = os.path.join(dataset_dir, "train")
validation_dir = os.path.join(dataset_dir, "validation")

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    train_dir,
    image_size=(150,150),
    batch_size=32
)

val_ds = tf.keras.preprocessing.image_dataset_from_directory(
    validation_dir,
    image_size=(150,150),
    batch_size=32
)

Exception: URL fetch failure on https://storage.googleapis.com/mledu-datasets/cats_and_dogs_filtered.zip: 403 -- Forbidden

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

for images, labels in test_ds.take(1):
    predictions = model.predict(images)

    predictions = (predictions > 0.5).astype(int)

    for i in range(len(images)):
        if predictions[i] != labels[i]:

            plt.imshow(images[i].numpy().astype("uint8"))
            plt.title(f"True: {labels[i].numpy()}, Pred: {predictions[i][0]}")
            plt.axis("off")
            plt.show()